### ISSUE TITLE
Default Memstore not loading in assumed order

### ISSUE THREAD

**Issue by mcdonnelldean** [senecajs/seneca-entity#23]
@rjrodger 

@mihaidma and I did some investigation. It seems trying to load memstore as we are now in the body of the plugin is not working correctly. It loads after the next plugin. The effect of this can be seen in seneca-user and seneca-auth failing tests. To fix, simply add MemStore to the tests.

The desired behaviour can be fixed by instead loading MemStore in the preload function of the plugin but in that case options are lost.

To resolve the current break we need to:

- Provide the options passed by the user to preload as well as the main plugin. 

- Mandate memstore must be loaded explicitly. Mandating explicit loading won't break back compat as mem store is loaded by seneca proper in previous versions.

What are your thoughts on this?

**Comment by rjrodger** [comment]
PR #24 should fix this
