### ISSUE TITLE
Unable to resolve module nid

### ISSUE THREAD

**Issue by LeonNimoy** [senecajs/seneca-entity#75]
Hey,

I tried to install this package in one of my projects, however, I getting the following error:

![error](https://user-images.githubusercontent.com/65237061/177058779-c616a351-bce9-416f-bb6f-707cece08d2a.png)

![stack](https://user-images.githubusercontent.com/65237061/177058791-674faf3f-147b-4aa5-8f1a-85ec4f1d783d.png)

I notice that the nid package is being used:
https://github.com/senecajs/seneca-entity/blob/668550f7ed8e7d9cb88871c9f7c7dc2df470a262/src/lib/common.ts#L4

However, the dependency isn't listed in the package.json.

**Comment by rjrodger** [comment]
thanks - fixed
